apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dev-container-templates
  namespace: default
  description: Software Templates (Golden Paths) CMA CGM — dev container
spec:
  targets:
    # Unitaires applicatifs
    - ./node-template/template.yaml
    - ./springboot-template/template.yaml
    - ./springboot-liquibase-template/template.yaml
    # Unitaires gateway & auth
    - ./kong-service-template/template.yaml
    - ./ping-federate-service-template/template.yaml
    # API-first (composition Kong + Ping)
    - ./api-contract-template/template.yaml
    - ./api-springboot-impl-template/template.yaml
    # Composites
    - ./springboot-liquibase-composition-template/template.yaml
