apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dev-container-templates
  namespace: default
  description: Software Templates (Golden Paths) CMA CGM — dev container
spec:
  targets:
    # Unitaires
    - ./node-template/template.yaml
    - ./springboot-template/template.yaml
    - ./springboot-liquibase-template/template.yaml
    - ./swagger-template/template.yaml
    # Composites
    - ./springboot-liquibase-composition-template/template.yaml
    - ./springboot-openapi-codegen-template/template.yaml
