apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - java
    - backend
    - openapi
  annotations:
    simpleicons.org/icon-slug: springboot
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  domain: ${{ values.domain }}
  providesApis:
    - api:default/${{ values.name }}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.system }}
  description: System grouping for ${{ values.name }}
spec:
  owner: ${{ values.owner }}
  domain: ${{ values.domain }}
