apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - openapi
  links:
{%- if values.repoProvider == 'github' %}
    - url: https://github.com/${{ values.repoOwner }}/${{ values.name }}
      title: Repository
      icon: github
{%- else %}
    - url: https://${{ values.gitlabHost }}/${{ values.repoOwner }}/${{ values.name }}
      title: Repository
      icon: gitlab
{%- endif %}
{%- if values.exposeViaKong %}
    - url: http://localhost:8000${{ values.kongRoutePath }}
      title: Kong Proxy URL
      icon: web
{%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    cma-cgm.com/api-type: ${{ values.apiType }}
    {%- if values.hopexComponentCode %}
    cma-cgm.com/hopex-code: ${{ values.hopexComponentCode }}
    {%- endif %}
{%- if values.exposeViaKong %}
    kong.io/service-name: ${{ values.name }}
    kong.io/route-path: ${{ values.kongRoutePath }}
    hip.io/access-scopes: ${{ values.accessScopes }}
    hip.io/auto-approve-scopes: ${{ values.autoApproveScopes }}
{%- endif %}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  domain: ${{ values.domain }}
  definition:
    $text: ./openapi.yaml
